### ISSUE TITLE
remove_policy 不可用 

### ISSUE THREAD

**Issue by learning233** [xingxingzaixian/FastAPI-MySQL-Tortoise-Casbin#1]
在这里得到 False

internal_enforcer.py

    def _remove_policy(self, sec, ptype, rule):
        """removes a rule from the current policy."""
        rule_removed = self.model.remove_policy(sec, ptype, rule)   # False
        if not rule_removed:
            return rule_removed

**Comment by xingxingzaixian** [comment]
已经修改使用asynccasbin库了
